
===========
       running command "/usr/bin/dunst -conf /home/sdsaati/.config/qtile/saati/../../dunstrc 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/xfsettingsd --daemon -D 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========
WARNING: Setting geometry in section global doesn't exist
WARNING: Setting notification_height in section global doesn't exist
WARNING: Setting startup_notification in section global doesn't exist
WARNING: Setting verbosity in section global doesn't exist
CRITICAL: [dbus_cb_name_lost:1152] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '9522'.

(xfsettingsd:9549): libxfce4kbd-private-WARNING **: 09:44:26.964: Failed to grab keycode 33

(xfsettingsd:9549): libxfce4kbd-private-WARNING **: 09:44:26.965: Failed to grab keycode 107

(xfsettingsd:9549): libxfce4kbd-private-WARNING **: 09:44:26.965: Failed to grab keycode 218
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

===========
       running command "/usr/bin/dbus-launch lxpolkit 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/pkexec --keep-cwd /usr/sbin/dnscrypt-proxy "-config /home/sdsaati/.config/qtile/saati/../../dnscrypt.toml" 2>>/home/sdsaati/.config/qtile/saati/startup_once.log"       
===========
(ERROR) Command 'nm-applet' not found.

===========
       running command "/home/sdsaati/bin/oblivion  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/nm-tray  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/nitrogen --restore 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/dropbox start 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/sbin/firefox  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/blueman-applet  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

(nitrogen:9589): GLib-GObject-CRITICAL **: 09:44:32.990: Attempting to freeze the notification queue for object GtkSettings[0x57cceab9c2b0]; Property notification does not work during instance finalization.

(nitrogen:9589): GLib-GObject-CRITICAL **: 09:44:32.990: Attempting to thaw the notification queue for object GtkSettings[0x57cceab9c2b0]; Property notification does not work during instance finalization.
blueman-applet 09.44.33 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/cryptography.hazmat.bindings._openssl.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/cryptography.hazmat.bindings._padding.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/apex._apex.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/psutil._psutil_linux.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/psutil._psutil_posix.cpython-38-x86_64-linux-gnu.so'
blueman-applet 09.44.33 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/google._upb._message.cpython-38-x86_64-linux-gnu.so'

(xfsettingsd:9549): libxfce4kbd-private-WARNING **: 09:44:34.543: Failed to grab keycode 33

(xfsettingsd:9549): libxfce4kbd-private-WARNING **: 09:44:34.544: Failed to grab keycode 107

(xfsettingsd:9549): libxfce4kbd-private-WARNING **: 09:44:34.544: Failed to grab keycode 218
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/tornado.speedups.cpython-38-x86_64-linux-gnu.so'
[2025-01-25 09:44:37] [NOTICE] dnscrypt-proxy 2.0.45
[2025-01-25 09:44:37] [NOTICE] Network connectivity detected
[2025-01-25 09:44:37] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2025-01-25 09:44:37] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
[2025-01-25 09:44:37] [NOTICE] Source [public-resolvers] loaded
[2025-01-25 09:44:37] [NOTICE] Firefox workaround initialized
[2025-01-25 09:44:37] [NOTICE] [google] OK (DoH) - rtt: 49ms
[2025-01-25 09:44:38] [NOTICE] [cloudflare] OK (DoH) - rtt: 99ms
[2025-01-25 09:44:38] [NOTICE] Sorted latencies:
[2025-01-25 09:44:38] [NOTICE] -    49ms google
[2025-01-25 09:44:38] [NOTICE] -    99ms cloudflare
[2025-01-25 09:44:38] [NOTICE] Server with the lowest initial latency: google (rtt: 49ms)
[2025-01-25 09:44:38] [NOTICE] dnscrypt-proxy is ready - live servers: 2
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/wrapt._wrappers.cpython-38-x86_64-linux-gnu.so'
WarpPlus error: {"data":{"parameters":{}},"noticeType":"ApplicationParameters","timestamp":"2025-01-25T06:14:43.366Z"}

dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtCore.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.sip.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtGui.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtWidgets.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtDBus.so'
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
[ERROR glean_core::metrics::ping] Invalid reason code inactive for ping usage-reporting
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
