
===========
       running command "/usr/bin/dunst -conf /home/sdsaati/.config/qtile/saati/../../dunstrc 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/xfsettingsd --daemon -D 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========
WARNING: Setting geometry in section global doesn't exist
WARNING: Setting notification_height in section global doesn't exist
WARNING: Setting startup_notification in section global doesn't exist
WARNING: Setting verbosity in section global doesn't exist
CRITICAL: [dbus_cb_name_lost:1152] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '1563'.

(xfsettingsd:1611): libxfce4kbd-private-WARNING **: 21:07:16.356: Failed to grab keycode 33

(xfsettingsd:1611): libxfce4kbd-private-WARNING **: 21:07:16.359: Failed to grab keycode 107

(xfsettingsd:1611): libxfce4kbd-private-WARNING **: 21:07:16.359: Failed to grab keycode 218
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

===========
       running command "/usr/bin/dbus-launch lxpolkit 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/pkexec --keep-cwd /usr/sbin/dnscrypt-proxy "-config /home/sdsaati/.config/qtile/saati/../../dnscrypt.toml" 2>>/home/sdsaati/.config/qtile/saati/startup_once.log"       
===========
(ERROR) Command 'nm-applet' not found.

===========
       running command "/home/sdsaati/bin/oblivion  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/nm-tray  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/pasystray  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/nitrogen --restore 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/dropbox start 2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/sbin/firefox  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

===========
       running command "/usr/bin/blueman-applet  2>>/home/sdsaati/.config/qtile/saati/startup_once.log & "      
===========

(nitrogen:2210): GLib-GObject-CRITICAL **: 21:07:22.069: Attempting to freeze the notification queue for object GtkSettings[0x6003464fb280]; Property notification does not work during instance finalization.

(nitrogen:2210): GLib-GObject-CRITICAL **: 21:07:22.069: Attempting to thaw the notification queue for object GtkSettings[0x6003464fb280]; Property notification does not work during instance finalization.
blueman-applet 21.07.22 WARNING  PluginManager:151 __load_plugin: Not loading DhcpClient because its conflict has higher priority

(pasystray:2206): Gdk-CRITICAL **: 21:07:22.314: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
blueman-applet 21.07.22 WARNING  PluginManager:151 __load_plugin: Not loading PPPSupport because its conflict has higher priority
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/cryptography.hazmat.bindings._openssl.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/cryptography.hazmat.bindings._padding.abi3.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/apex._apex.abi3.so'

(xfsettingsd:1611): libxfce4kbd-private-WARNING **: 21:07:23.610: Failed to grab keycode 33

(xfsettingsd:1611): libxfce4kbd-private-WARNING **: 21:07:23.612: Failed to grab keycode 107

(xfsettingsd:1611): libxfce4kbd-private-WARNING **: 21:07:23.613: Failed to grab keycode 218
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/psutil._psutil_linux.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/psutil._psutil_posix.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/google._upb._message.cpython-38-x86_64-linux-gnu.so'
[2025-02-01 21:07:24] [NOTICE] dnscrypt-proxy 2.0.45
[2025-02-01 21:07:24] [NOTICE] Network connectivity detected
[2025-02-01 21:07:24] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
[2025-02-01 21:07:24] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/tornado.speedups.cpython-38-x86_64-linux-gnu.so'
[ERROR glean_core::metrics::ping] Invalid reason code active for ping usage-reporting
[2025-02-01 21:07:34] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [download.dnscrypt.info] using fallback resolvers over udp
[2025-02-01 21:07:35] [NOTICE] Source [public-resolvers] loaded
[2025-02-01 21:07:35] [NOTICE] Firefox workaround initialized
[2025-02-01 21:07:36] [NOTICE] [google] OK (DoH) - rtt: 53ms
[2025-02-01 21:07:36] [NOTICE] [cloudflare] OK (DoH) - rtt: 109ms
[2025-02-01 21:07:36] [NOTICE] Sorted latencies:
[2025-02-01 21:07:36] [NOTICE] -    53ms google
[2025-02-01 21:07:36] [NOTICE] -   109ms cloudflare
[2025-02-01 21:07:36] [NOTICE] Server with the lowest initial latency: google (rtt: 53ms)
[2025-02-01 21:07:36] [NOTICE] dnscrypt-proxy is ready - live servers: 2
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/wrapt._wrappers.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtCore.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.sip.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtGui.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtWidgets.so'
dropbox: load fq extension '/home/sdsaati/.dropbox-dist/dropbox-lnx.x86_64-216.4.4420/PyQt5.QtDBus.so'
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
